### ISSUE TITLE
Multi-Vendor tabulation fails due to Candidate Names

### ISSUE THREAD

**Issue by rrojas350** [BrightSpots/rcv#628]
When tabulating multi-vendor CVRs, ES&S and Hart, for the same race RCTab will error out for either duplicate candidate names or unknown candidate names found. Hart uses both candidate names and candidate codes while ES&S uses only candidate names. See the attached audit logs for more info. 
[2023-02-06_13-22-23_audit_0.log](https://github.com/BrightSpots/rcv/files/10679940/2023-02-06_13-22-23_audit_0.log)
[2023-02-06_13-14-58_audit_0.log](https://github.com/BrightSpots/rcv/files/10679944/2023-02-06_13-14-58_audit_0.log)

**Comment by tarheel** [comment]
Could you provide the config file + CVR source files that reproduce this bug?

**Comment by rrojas350** [comment]
Here you go:

[https://drive.google.com/drive/folders/1lPywmHSX5HYRlfEMWU27bVGbqOtNQiD9?usp=sharing](Multi-Vendor CVR)

**Comment by rrojas350** [comment]
Sure. Here you go:

[Hart and ES&S CVR](https://drive.google.com/drive/folders/1lPywmHSX5HYRlfEMWU27bVGbqOtNQiD9?usp=sharing)

I used version 1.2 to keep in line with what VA is currently using but ran into the same issue with 1.3.

**Comment by artoonie** [comment]
By a happy accident - it seems the fix for #591 works well for this case.

The issue was because previously, you had to choose between either having a code or a candidate name, so this didn't mix well across vendors.

With the new concept of aliases, this problem goes away. It takes a small change to the config file, but the following update to `candidates` in the config you provided on the #591 branch successfully tabulates:

```
  "candidates" : [ {
    "name" : "Christian Edgar Dorsey",
    "excluded" : false,
    "aliases" : [ ],
    "code" : "bfc47c9d-ca6e-41ed-a449-3605e2234791"
  }, {
    "name" : "Peter Charles Fallon",
    "excluded" : false,
    "aliases" : [ ],
    "code" : "e5868eb9-d8b1-402c-a373-3fd85ca362d3"
  }, {
    "name" : "Bruce Alan Wiljanen",
    "excluded" : false,
    "aliases" : [ ],
    "code" : "39c15fe1-17a1-4915-9e98-e9aea4d8a553"
  }, {
    "name" : "Kate Allison Cristol",
    "excluded" : false,
    "aliases" : [ ],
    "code" : "3ad696f4-8424-45d5-8451-5ad4c510f4f1"
  }, {
    "name" : "Takis Panagiotis Karantonis",
    "excluded" : false,
    "aliases" : [ "9d0efd82-b6a9-4167-aa29-d35131a47af9", "Takis Karantonis" ]
  }, {
    "name" : "Chandra Choun",
    "excluded" : false,
    "aliases" : [ "Chanda Choun", "a196acc9-b39f-4b9d-a6b9-b1966ce99bc4" ]
  }, {
    "name" : "Andrew Frithjof Schneider",
    "excluded" : false,
    "aliases" : [ "ef060640-315c-4121-98a3-5fd9e51340d1", "Andrew Schneider" ]
  } ],
```

I believe we can call this closed without needing any additional code.

**Comment by HEdingfield** [comment]
@artoonie is this issue fully resolved now with #591, or are there loose ends we need to take care of?

**Comment by artoonie** [comment]
IMO we can call this closed. The specific config files still fail, but those are impossible to generate now.

**Comment by HEdingfield** [comment]
Good deal! I wanted to confirm because it looks like the fix you described [here](https://github.com/BrightSpots/rcv/issues/628#issuecomment-1471227176) still has `code` fields in the config, which I don't believe exist anymore...

If that still looks good to you, I'll let you have the honor of closing this out. 👍

**Comment by artoonie** [comment]
I have kept support for configs with `code` to support legacy configs, though I'd like to create a real migration system where we take raw JSON and output raw JSON, eliminating the need for the codebase itself to support any legacy formats. A task for another day (I'll create an issue!).
